// Open the link(s) generated by demus-coverter, open and paste this into a developer console,
// change PLAYLIST_INDEX, wait ~1min, and all the videos should be added to your playlist.
// The index of the playlist you want to save the videos to.
// To find this, go to any random youtube video, click the save button,
// and find the playlist that you want to save the songs to.
// The index is the number of spots the playlist is from the top, starting at 0.
// 0 should usually refer to Watch Later if you haven't ever moved it, 
// 1 is the playlist below Watch Later, 2 is the one after that, etc.
const PLAYLIST_INDEX = 0;

let b = document.querySelectorAll("button[aria-label='Action menu']"); let i = 0; const w = () => new Promise(r=>setTimeout(r,300)); const c = async () => { b[i].click(); await w(); document.querySelectorAll("a.yt-simple-endpoint.style-scope.ytd-menu-navigation-item-renderer")[0].click(); await w(); document.querySelectorAll("button.ytButtonOrAnchorHost.ytButtonOrAnchorButton.ytListItemViewModelButtonOrAnchor.ytListItemViewModelTextWrapper")[PLAYLIST_INDEX].click(); await w(); i++; if (i != 49) c() }; c()