// Open the link(s) generated by demus-coverter, open and paste this into a developer console,
// change PLAYLIST_INDEX, wait ~1min (do not change tabs or do anything), 
// and all the videos should be added to your playlist.

// PLAYLIST_INDEX is the index of the playlist you want to save the videos to.
// To find this, go to any random youtube video, click the save button,
// and find the playlist that you want to save the songs to.
// The index is the number of spots the playlist is from the top, starting at 0.
// 0 should refer to Watch Later 
// 1 is the playlist below Watch Later (generally your most recently created one), 2 is the one after that, etc.
const PLAYLIST_INDEX = CHANGE_ME;

let b = document.querySelectorAll("button[aria-label='Action menu']");
let i = 0;
// ~500ms is what seems to work for me,
// increase/decrease the timeout if you are more/less laggy than me
const w = () => new Promise(r=>setTimeout(r,500));
const wf = () => new Promise(r=>requestAnimationFrame(r))
const c = async () => {
    b[i].scrollIntoView()
    b[i].click();
    await w();
    document.querySelectorAll("a.yt-simple-endpoint.style-scope.ytd-menu-navigation-item-renderer")[0].click();
    await w();
    document.querySelectorAll("button.ytButtonOrAnchorHost.ytButtonOrAnchorButton.ytListItemViewModelButtonOrAnchor.ytListItemViewModelTextWrapper")
        [PLAYLIST_INDEX].click();
    i++; 
    await w();
    if (i != 50) c()
};
c()
